import { NextResponse } from "next/server";
import { Prisma } from "@/generated/prisma/client";
import { requireSession } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { extractImageUrls, generateImageUrls } from "@/lib/image-urls";
import { validatePhysicalData } from "@/lib/validation";

function text(data:unknown,key:string){return String((data as Record<string,unknown>|null)?.[key]??"").trim()}
function flexibleId(data:unknown,configured:string){const row=(data??{}) as Record<string,unknown>;if(configured&&text(row,configured))return text(row,configured);const key=Object.keys(row).find((name)=>(/(^id$|\bid$)/i).test(name.trim()));return key?text(row,key):""}

export async function GET(request:Request){
  try{
    await requireSession();const params=new URL(request.url).searchParams;const mode=params.get("mode")==="validation"?"validation":"pending";const page=Math.max(1,Number(params.get("page")??1));const pageSize=Math.min(100,Math.max(1,Number(params.get("pageSize")??50)));const indicator=params.get("indicator")??"";
    const run=await prisma.syncRun.findFirst({where:{status:{in:["COMPLETED","PARTIAL"]}},orderBy:{createdAt:"desc"}});if(!run)return NextResponse.json({items:[],total:0,page:1,pageSize,indicators:{},options:{brands:[],classifications:[]},run:null});
    const [inactive,settings,seniorSource,tinySource,unavailableChecks,availableChecks,approvedOverrides]=await Promise.all([
      prisma.productOverride.findMany({where:{excludedFromAnalysis:true},select:{skuKey:true}}),prisma.appSetting.findUnique({where:{key:"content"}}),prisma.dataSource.findUnique({where:{type:"SENIOR"}}),prisma.dataSource.findUnique({where:{type:"TINY"}}),
      prisma.imageCheck.findMany({where:{available:false,urlsSignature:{startsWith:"v3:"}},select:{skuKey:true}}),prisma.imageCheck.findMany({where:{available:true,urlsSignature:{startsWith:"v3:"}},select:{skuKey:true}}),prisma.productOverride.findMany({where:{approvedDescription:{not:null}},select:{skuKey:true,approvedDescription:true}}),
    ]);
    const inactiveKeys=inactive.map((item)=>item.skuKey);const unavailableKeys=unavailableChecks.map((item)=>item.skuKey);const availableKeys=new Set(availableChecks.map((item)=>item.skuKey));const approvedKeys=new Set(approvedOverrides.filter((item)=>Boolean(item.approvedDescription?.trim())).map((item)=>item.skuKey));
    const readyRows=await prisma.productSnapshot.findMany({where:{syncRunId:run.id,productStatus:"READY"},select:{skuKey:true}});const noReviewKeys=readyRows.map((item)=>item.skuKey).filter((key)=>approvedKeys.has(key)&&availableKeys.has(key));
    const base:Prisma.ProductSnapshotWhereInput=mode==="validation"?{syncRunId:run.id,comparisonStatus:{in:["CORRECT","ID_DIVERGENT","ID_MISSING"]},skuKey:{notIn:inactiveKeys}}:{syncRunId:run.id,comparisonStatus:"PENDING_TINY",skuKey:{notIn:inactiveKeys}};
    const conditions:Prisma.ProductSnapshotWhereInput[]=[base];const search=(params.get("search")??"").trim();if(search)conditions.push({OR:[{sku:{contains:search,mode:"insensitive"}},{ean:{contains:search,mode:"insensitive"}},{name:{contains:search,mode:"insensitive"}}]});
    const brand=params.get("brand");if(brand)conditions.push({brand});const classification=params.get("classification");if(classification)conditions.push({classification});const stock=params.get("stock");if(stock==="positive")conditions.push({stock:{gt:0}});if(stock==="zero")conditions.push({OR:[{stock:null},{stock:{lte:0}}]});const review=params.get("review");if(review==="yes")conditions.push({skuKey:{notIn:noReviewKeys}});if(review==="no")conditions.push({skuKey:{in:noReviewKeys}});
    if(indicator==="baseline")conditions.push({classification:{equals:"baseline",mode:"insensitive"}});if(indicator==="launch")conditions.push({OR:["new","launch","lauch"].map((value)=>({classification:{equals:value,mode:"insensitive"}}))});if(indicator==="phaseout-stock")conditions.push({classification:{equals:"phase out",mode:"insensitive"},stock:{gt:0}});if(indicator==="unclassified-stock")conditions.push({OR:[{classification:null},{classification:""}],stock:{gt:0}});if(indicator==="images-unavailable")conditions.push({skuKey:{in:unavailableKeys}});if(indicator==="id-divergent")conditions.push({comparisonStatus:"ID_DIVERGENT"});
    const where:Prisma.ProductSnapshotWhereInput={AND:conditions};
    if(params.get("keys")==="1"){const rows=await prisma.productSnapshot.findMany({where,select:{skuKey:true},take:20000});return NextResponse.json({skuKeys:rows.map((item)=>item.skuKey)})}
    const pendingBase:Prisma.ProductSnapshotWhereInput={syncRunId:run.id,comparisonStatus:"PENDING_TINY",skuKey:{notIn:inactiveKeys}};const validationBase:Prisma.ProductSnapshotWhereInput={syncRunId:run.id,comparisonStatus:{in:["CORRECT","ID_DIVERGENT","ID_MISSING"]},skuKey:{notIn:inactiveKeys}};
    const [total,items,baseline,launch,phaseout,unclassified,imagesUnavailable,divergent,brandRows,classRows]=await Promise.all([
      prisma.productSnapshot.count({where}),prisma.productSnapshot.findMany({where,orderBy:[{stock:"desc"},{name:"asc"}],skip:(page-1)*pageSize,take:pageSize}),
      prisma.productSnapshot.count({where:{AND:[pendingBase,{classification:{equals:"baseline",mode:"insensitive"}}]}}),prisma.productSnapshot.count({where:{AND:[pendingBase,{OR:["new","launch","lauch"].map((value)=>({classification:{equals:value,mode:"insensitive"}}))}]}}),prisma.productSnapshot.count({where:{AND:[pendingBase,{classification:{equals:"phase out",mode:"insensitive"},stock:{gt:0}}]}}),prisma.productSnapshot.count({where:{AND:[pendingBase,{OR:[{classification:null},{classification:""}],stock:{gt:0}}]}}),prisma.productSnapshot.count({where:{AND:[pendingBase,{skuKey:{in:unavailableKeys}}]}}),prisma.productSnapshot.count({where:{AND:[validationBase,{comparisonStatus:"ID_DIVERGENT"}]}}),
      prisma.productSnapshot.findMany({where:base,select:{brand:true},distinct:["brand"]}),prisma.productSnapshot.findMany({where:base,select:{classification:true},distinct:["classification"]}),
    ]);
    const keys=items.map((item)=>item.skuKey);const [overrides,generations,imageChecks]=await Promise.all([prisma.productOverride.findMany({where:{skuKey:{in:keys}}}),prisma.aiGeneration.findMany({where:{skuKey:{in:keys},status:"COMPLETED"},orderBy:{createdAt:"desc"}}),prisma.imageCheck.findMany({where:{skuKey:{in:keys}}})]);const overrideMap=new Map(overrides.map((item)=>[item.skuKey,item]));const imageCheckMap=new Map(imageChecks.map((item)=>[item.skuKey,item]));const aiMap=new Map<string,string>();for(const item of generations)if(item.output&&!aiMap.has(item.skuKey))aiMap.set(item.skuKey,item.output);
    const config=(settings?.value??{}) as Record<string,unknown>;const seniorMap=(seniorSource?.columnMapping??{}) as Record<string,string>;const seniorIdHeader=String(seniorMap.tinyId??"");const tinyIdHeader=String(((tinySource?.columnMapping??{}) as Record<string,string>).tinyId??"");
    const result=items.map((item)=>{const override=overrideMap.get(item.skuKey);const physical=validatePhysicalData({weight:override?.weight??text(item.seniorData,seniorMap.weight??"weight"),length:override?.length??text(item.seniorData,seniorMap.length??"length"),width:override?.width??text(item.seniorData,seniorMap.width??"width"),height:override?.height??text(item.seniorData,seniorMap.height??"height")});const generated=generateImageUrls({pattern:String(config.imageUrlPattern??""),sku:item.sku,ean:item.ean,count:Number(config.imageCount??5),start:Number(config.imageStart??1),extension:String(config.imageExtension??"jpg")});const imageUrls=(override?.imageUrls as string[]|null)??[...new Set([...extractImageUrls(item.tinyData),...extractImageUrls(item.seniorData),...generated])];const check=imageCheckMap.get(item.skuKey);const imagesChecked=check?.urlsSignature===`v3:${JSON.stringify(imageUrls)}`;const seniorId=flexibleId(item.seniorData,seniorIdHeader);const tinyId=flexibleId(item.tinyData,tinyIdHeader);const validationStatus=!seniorId&&tinyId?"ID_MISSING":seniorId&&tinyId&&seniorId!==tinyId?"ID_DIVERGENT":seniorId&&tinyId?"CORRECT":"ID_UNAVAILABLE";return{id:item.id,sku:item.sku,skuKey:item.skuKey,ean:item.ean,name:item.name,brand:item.brand,classification:item.classification,stock:item.stock,price:item.price,comparisonStatus:item.comparisonStatus,override,aiDescription:aiMap.get(item.skuKey)??null,physicalIssues:physical.issues,physicalValues:physical.values,imageUrls,imagesChecked,allImagesUnavailable:imagesChecked&&!check?.available,availableImageUrl:imagesChecked?check?.availableUrl??null:null,needsReview:!noReviewKeys.includes(item.skuKey),validationStatus,seniorTinyId:seniorId,tinyId}});
    return NextResponse.json({items:result,total,page,pageSize,totalPages:Math.max(1,Math.ceil(total/pageSize)),indicators:{baseline,launch,phaseout,unclassified,imagesUnavailable,divergent},options:{brands:brandRows.map((item)=>item.brand).filter(Boolean).sort(),classifications:classRows.map((item)=>item.classification).filter(Boolean).sort()},run:{id:run.id,createdAt:run.createdAt,finishedAt:run.finishedAt}});
  }catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Não autorizado."},{status:400})}
}
