"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, KeyRound, TestTube2, Trash2 } from "lucide-react";

export function OpenAIConfigForm() {
  const [configured, setConfigured] = useState(false); const [stored, setStored] = useState(false); const [model, setModel] = useState("gpt-5.6-sol"); const [apiKey, setApiKey] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  useEffect(() => { fetch("/api/openai-config").then((response) => response.json()).then((data) => { setConfigured(Boolean(data.configured)); setStored(Boolean(data.storedInSystem)); if (data.model) setModel(data.model); }); }, []);
  async function save(event: React.FormEvent) { event.preventDefault(); setLoading(true); setMessage("Testando a chave…"); const response = await fetch("/api/openai-config", { method:"PUT", headers:{"content-type":"application/json"}, body:JSON.stringify({apiKey,model}) }); const data=await response.json(); if(response.ok){setConfigured(true);setStored(true);setApiKey("");setMessage("Chave validada, criptografada e salva com sucesso.")}else setMessage(data.error);setLoading(false); }
  async function test() { setLoading(true); const response=await fetch("/api/openai-config",{method:"POST"});const data=await response.json();setMessage(response.ok?`Conexão funcionando. Modelo configurado: ${data.model}.`:data.error);setLoading(false); }
  async function remove() { if(!confirm("Remover a chave da OpenAI salva no sistema?"))return;const response=await fetch("/api/openai-config",{method:"DELETE"});if(response.ok){setConfigured(false);setStored(false);setMessage("Chave removida do sistema.")} }
  return <section className="card space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-black"><KeyRound size={20}/>Integração OpenAI</h2><p className="mt-1 text-sm text-gray-500">Usada para gerar descrições comerciais dentro da revisão.</p></div><span className={configured?"badge badge-green":"badge badge-red"}>{configured?"Configurada":"Não configurada"}</span></div>
    <div className="rounded-xl bg-gray-50 p-4 text-sm text-gray-600"><p>A assinatura do ChatGPT e a API são cobradas separadamente. Crie a chave em <a className="font-bold text-[#1fadad] underline" href="https://platform.openai.com/api-keys" target="_blank" rel="noreferrer">platform.openai.com/api-keys</a> e confirme o faturamento da API antes de salvar.</p></div>
    {message&&<p className="rounded-xl bg-[#e7f8f8] p-3 text-sm font-semibold text-[#147f81]">{message}</p>}
    <form className="space-y-4" onSubmit={save}><div><label className="label">Chave secreta da API</label><input className="input" type="password" value={apiKey} onChange={(event)=>setApiKey(event.target.value)} placeholder={stored?"Uma chave já está salva — informe outra para substituir":"sk-..."} autoComplete="off" required/><p className="mt-1 text-xs text-gray-500">A chave é enviada somente ao servidor e armazenada criptografada. Ela nunca volta a aparecer nesta tela.</p></div><div><label className="label">Modelo</label><input className="input" value={model} onChange={(event)=>setModel(event.target.value)} required/></div><div className="flex flex-wrap gap-2"><button className="btn btn-primary" disabled={loading||!apiKey}><CheckCircle2 size={16}/>{loading?"Validando…":"Testar e salvar"}</button>{configured&&<button className="btn btn-secondary" type="button" disabled={loading} onClick={test}><TestTube2 size={16}/>Testar conexão atual</button>}{stored&&<button className="btn btn-danger" type="button" onClick={remove}><Trash2 size={16}/>Remover chave</button>}</div></form>
  </section>;
}
