"use client";
import { useEffect, useMemo, useState } from "react";
import { X } from "lucide-react";

type Override = {weight:string|null;length:string|null;width:string|null;height:string|null;additionalInformation:string|null;approvedDescription:string|null;imageUrls:string[]|null};
type Product={id:string;sku:string;skuKey:string;ean:string|null;name:string;brand:string|null;classification:string|null;stock:string|null;price:string|null;cost:string|null;comparisonStatus:string;productStatus:string;physicalIssues:Record<string,string>|null;seniorData:Record<string,unknown>;override:Override|null;aiDescription:string|null};

function ProductEditor({product,onClose}:{product:Product;onClose:()=>void}){
  const [message,setMessage]=useState("");
  async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const number=(key:string)=>data[key]?Number(String(data[key]).replace(",",".")):null;const body={sku:product.sku,weight:number("weight"),length:number("length"),width:number("width"),height:number("height"),additionalInformation:data.additionalInformation,approvedDescription:data.approvedDescription,imageUrls:String(data.imageUrls??"").split("\n").map(v=>v.trim()).filter(Boolean)};const r=await fetch("/api/product-overrides",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await r.json();setMessage(r.ok?"Dados complementares salvos.":result.error)}
  const raw=product.seniorData;return <div className="fixed inset-0 z-50 flex justify-end bg-black/40"><div className="h-full w-full max-w-2xl overflow-auto bg-white p-6 shadow-2xl"><div className="mb-6 flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-orange-600">{product.sku}</p><h2 className="mt-1 text-2xl font-black">{product.name}</h2></div><button className="rounded-full p-2 hover:bg-gray-100" onClick={onClose}><X/></button></div><form className="space-y-5" onSubmit={save}>{message&&<p className="rounded-lg bg-green-50 p-3 text-sm text-green-700">{message}</p>}<div><h3 className="mb-3 font-bold">Peso e dimensões</h3><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{["weight","length","width","height"].map(key=><div key={key}><label className="label">{key}</label><input className="input" name={key} inputMode="decimal" defaultValue={String(product.override?.[key as keyof Override]??raw[key]??"")}/>{product.physicalIssues?.[key]&&<p className="mt-1 text-xs text-red-600">{product.physicalIssues[key]}</p>}</div>)}</div></div><div><label className="label">Informações adicionais para a IA</label><textarea className="input min-h-28" name="additionalInformation" defaultValue={product.override?.additionalInformation??""}/></div><div><label className="label">Descrição aprovada</label><textarea className="input min-h-52" name="approvedDescription" defaultValue={product.override?.approvedDescription??product.aiDescription??""}/><p className="mt-1 text-xs text-gray-500">A geração da IA só entra na exportação depois de ser revisada e salva aqui.</p></div><div><label className="label">Links externos — um por linha</label><textarea className="input min-h-28" name="imageUrls" defaultValue={product.override?.imageUrls?.join("\n")??""}/></div><div className="flex gap-2"><button className="btn btn-primary">Salvar revisão</button><button className="btn btn-secondary" type="button" onClick={onClose}>Fechar</button></div></form></div></div>}

export function ProductsTable({mode="pending"}:{mode?:"pending"|"validation"}){const [items,setItems]=useState<Product[]>([]);const [search,setSearch]=useState("");const [selected,setSelected]=useState<string[]>([]);const [loading,setLoading]=useState(true);const [editing,setEditing]=useState<Product|null>(null);useEffect(()=>{fetch(`/api/products?mode=${mode}`).then(r=>r.json()).then(d=>setItems(d.items??[])).finally(()=>setLoading(false))},[mode]);const visible=useMemo(()=>items.filter(i=>`${i.sku} ${i.ean} ${i.name}`.toLowerCase().includes(search.toLowerCase())),[items,search]);async function ai(){const r=await fetch("/api/ai/descriptions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({skuKeys:selected})});const d=await r.json();alert(r.ok?`${d.generated} descrições geradas. Abra Revisar para aprovar.`:d.error)}async function exportSelected(){const r=await fetch("/api/exports",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({skuKeys:selected})});const d=await r.json();if(!r.ok)return alert(d.error);location.href=d.downloadUrl}
  return <>{editing&&<ProductEditor product={editing} onClose={()=>setEditing(null)}/>}<div className="card mb-4 flex flex-col gap-3 md:flex-row md:items-center"><input className="input md:max-w-sm" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por SKU, EAN ou produto"/><div className="flex flex-1 flex-wrap gap-2 md:justify-end"><button className="btn btn-secondary" onClick={()=>setSelected(visible.map(i=>i.skuKey))}>Selecionar visíveis</button>{mode==="pending"&&<><button className="btn btn-secondary" disabled={!selected.length} onClick={ai}>Gerar descrição IA</button><button className="btn btn-primary" disabled={!selected.length} onClick={exportSelected}>Exportar {selected.length||""}</button></>}</div></div><div className="table-wrap">{loading?<p className="p-8 text-center text-gray-500">Carregando…</p>:<table><thead><tr>{mode==="pending"&&<th></th>}<th>SKU</th><th>EAN</th><th>Produto</th><th>Marca</th><th>Classificação</th><th>Estoque</th><th>Preço</th><th>Status</th><th></th></tr></thead><tbody>{visible.length?visible.map(item=><tr key={item.id} className={Number(item.stock)>0?"bg-orange-50/40":""}>{mode==="pending"&&<td><input type="checkbox" checked={selected.includes(item.skuKey)} onChange={e=>setSelected(s=>e.target.checked?[...s,item.skuKey]:s.filter(k=>k!==item.skuKey))}/></td>}<td className="font-bold">{item.sku}</td><td>{item.ean||"—"}</td><td><div className="font-semibold">{item.name}</div>{item.physicalIssues&&Object.keys(item.physicalIssues).length>0&&<span className="badge badge-red mt-1">Medidas para revisar</span>}</td><td>{item.brand||"—"}</td><td>{item.classification||"—"}</td><td className="font-bold">{item.stock??"—"}</td><td>{item.price?`R$ ${item.price}`:"—"}</td><td><span className={item.comparisonStatus.includes("MATCHED")||item.comparisonStatus==="CORRECT"?"badge badge-green":item.comparisonStatus==="PENDING_TINY"?"badge badge-orange":"badge badge-red"}>{item.comparisonStatus}</span></td><td><button className="font-bold text-orange-600" onClick={()=>setEditing(item)}>Revisar</button></td></tr>):<tr><td colSpan={10} className="py-12 text-center text-gray-500">Nenhum registro. Configure as fontes e execute uma atualização.</td></tr>}</tbody></table>}</div></>}
