"use client";
/* eslint-disable @next/next/no-img-element */

import { useCallback, useEffect, useState } from "react";
import { Ban, Check, Sparkles, Trash2, X } from "lucide-react";

type Override = { weight: string | null; length: string | null; width: string | null; height: string | null; additionalInformation: string | null; approvedDescription: string | null; imageUrls: string[] | null };
type Product = { id:string; sku:string; skuKey:string; ean:string|null; name:string; brand:string|null; classification:string|null; stock:string|null; price:string|null; comparisonStatus:string; physicalIssues:Record<string,string>|null; physicalValues:Record<string,number|null>; override:Override|null; aiDescription:string|null; imageUrls:string[]; imagesChecked:boolean; allImagesUnavailable:boolean; availableImageUrl:string|null; needsReview:boolean; validationStatus?:string; seniorTinyId?:string; tinyId?:string };
type Indicator = "baseline"|"launch"|"phaseout-stock"|"unclassified-stock"|"images-unavailable"|"id-divergent"|"";

function ProductEditor({ product, onClose, onSaved }: { product: Product; onClose: () => void; onSaved: (message: string) => void }) {
  const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false); const [generating, setGenerating] = useState(false);
  const [images, setImages] = useState(product.imageUrls); const [broken, setBroken] = useState<string[]>([]);
  const [draft, setDraft] = useState(product.override?.approvedDescription ?? product.aiDescription ?? "");
  const [approved, setApproved] = useState(product.override?.approvedDescription ?? "");
  const initial = (key: keyof Product["physicalValues"]) => product.override?.[key as keyof Override] ?? product.physicalValues[key] ?? "";

  function payload(form: HTMLFormElement) { const data = Object.fromEntries(new FormData(form)); const number = (key:string) => String(data[key] ?? "").trim() ? Number(String(data[key]).replace(",", ".")) : null; return { sku:product.sku, weight:number("weight"), length:number("length"), width:number("width"), height:number("height"), additionalInformation:String(data.additionalInformation ?? ""), approvedDescription:approved, imageUrls:images }; }
  async function persist(form: HTMLFormElement) { const response = await fetch("/api/product-overrides", { method:"PUT", headers:{"content-type":"application/json"}, body:JSON.stringify(payload(form)) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Não foi possível salvar."); }
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(""); try { await persist(event.currentTarget); onSaved("Revisão salva com sucesso."); onClose(); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível salvar."); } finally { setSaving(false); } }
  async function generate(form: HTMLFormElement) { setGenerating(true); setMessage("Salvando informações e gerando descrição…"); try { await persist(form); const response = await fetch("/api/ai/descriptions", { method:"POST", headers:{"content-type":"application/json"}, body:JSON.stringify({skuKeys:[product.skuKey]}) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); const output = data.outputs?.[product.skuKey]; if (!output) throw new Error(data.errors?.[0] ?? "A IA não retornou uma descrição."); setDraft(output); setMessage("Descrição gerada. Revise e clique em Aprovar."); } catch (error) { setMessage(error instanceof Error ? error.message : "Falha ao gerar descrição."); } finally { setGenerating(false); } }
  async function approve() { if (!draft.trim()) return; const response = await fetch("/api/ai/descriptions", { method:"PUT", headers:{"content-type":"application/json"}, body:JSON.stringify({skuKey:product.skuKey,description:draft}) }); const data = await response.json(); if (response.ok) { setApproved(draft); setMessage("Descrição aprovada e pronta para exportação."); } else setMessage(data.error); }

  return <div className="fixed inset-0 z-50 flex justify-end bg-black/50"><div className="h-full w-full max-w-3xl overflow-auto bg-white p-6 shadow-2xl">
    <div className="mb-6 flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#1fadad]">{product.sku}</p><h2 className="mt-1 text-2xl font-black">{product.name}</h2></div><button aria-label="Fechar" className="rounded-full p-2 hover:bg-gray-100" onClick={onClose}><X /></button></div>
    <form className="space-y-6" onSubmit={save}>{message && <p className="rounded-lg bg-[#e7f8f8] p-3 text-sm font-semibold text-[#147f81]">{message}</p>}
      <section><h3 className="mb-3 font-bold">Informações físicas</h3><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{(["weight","length","width","height"] as const).map((key) => <div key={key}><label className="label">{{weight:"Peso",length:"Comprimento",width:"Largura",height:"Altura"}[key]}</label><input className="input" name={key} inputMode="decimal" defaultValue={String(initial(key))} />{product.physicalIssues?.[key] && <p className="mt-1 text-xs text-red-600">{product.physicalIssues[key]}</p>}</div>)}</div></section>
      <section><label className="label">Informações adicionais para a IA</label><textarea className="input min-h-28" name="additionalInformation" defaultValue={product.override?.additionalInformation ?? ""} /></section>
      <section className="rounded-xl border border-[#dfe4e8] p-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><h3 className="font-bold">Descrição comercial</h3><button className="btn btn-secondary" type="button" disabled={generating} onClick={(event) => generate(event.currentTarget.form!)}><Sparkles size={16} />{generating ? "Gerando…" : draft ? "Gerar nova" : "Gerar descrição"}</button></div><textarea className="input min-h-52" value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="A descrição gerada aparecerá aqui." />
        <div className="mt-3 flex items-center gap-3"><button className="btn btn-primary" type="button" disabled={!draft.trim() || draft === approved} onClick={approve}><Check size={16} />Aprovar descrição</button>{draft === approved && approved && <span className="badge badge-green">Aprovada para exportação</span>}</div>
      </section>
      <section><h3 className="mb-1 font-bold">Imagens do produto</h3><p className="mb-3 text-sm text-gray-500">Apague imagens incorretas ou indisponíveis. Somente as restantes serão exportadas.</p><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{images.map((url) => <div className="relative overflow-hidden rounded-xl border bg-gray-50" key={url}><img src={url} alt={product.name} className="aspect-square w-full object-contain" onError={() => setBroken((current) => current.includes(url) ? current : [...current, url])} />{broken.includes(url) && <span className="absolute inset-x-2 bottom-2 rounded bg-red-600 px-2 py-1 text-center text-xs font-bold text-white">Imagem indisponível</span>}<button type="button" aria-label="Excluir imagem" className="absolute right-2 top-2 rounded-full bg-white p-2 text-red-600 shadow" onClick={() => setImages((current) => current.filter((item) => item !== url))}><Trash2 size={16} /></button></div>)}</div>{!images.length && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">Nenhuma imagem será enviada ao Tiny.</p>}</section>
      <div className="flex gap-2"><button className="btn btn-primary" disabled={saving}>{saving ? "Salvando…" : "Salvar revisão"}</button><button className="btn btn-secondary" type="button" onClick={onClose}>Cancelar</button></div>
    </form>
  </div></div>;
}

export function ProductsTable({ mode="pending" }: { mode?:"pending"|"validation" }) {
  const [items,setItems]=useState<Product[]>([]); const [search,setSearch]=useState(""); const [selected,setSelected]=useState<string[]>([]); const [loading,setLoading]=useState(true); const [editing,setEditing]=useState<Product|null>(null); const [toast,setToast]=useState("");
  const [run,setRun]=useState<{id:string;finishedAt:string|null}|null>(null);
  const [brand,setBrand]=useState(""); const [classification,setClassification]=useState(""); const [stock,setStock]=useState(""); const [review,setReview]=useState("");
  const [indicator,setIndicator]=useState<Indicator>("");
  const [page,setPage]=useState(1);const [total,setTotal]=useState(0);const [totalPages,setTotalPages]=useState(1);const [options,setOptions]=useState<{brands:string[];classifications:string[]}>({brands:[],classifications:[]});const [indicatorCounts,setIndicatorCounts]=useState({baseline:0,launch:0,phaseout:0,unclassified:0,imagesUnavailable:0,divergent:0});
  const query=useCallback((withPage=true)=>{const params=new URLSearchParams({mode,pageSize:"50"});if(withPage)params.set("page",String(page));if(search)params.set("search",search);if(brand)params.set("brand",brand);if(classification)params.set("classification",classification);if(stock)params.set("stock",stock);if(review)params.set("review",review);if(indicator)params.set("indicator",indicator);return params},[mode,page,search,brand,classification,stock,review,indicator]);
  const load=useCallback(async(silent=false)=>{if(!silent)setLoading(true);const response=await fetch(`/api/products?${query()}`,{cache:"no-store"});const data=await response.json();setItems(data.items??[]);setRun(data.run??null);setTotal(data.total??0);setTotalPages(data.totalPages??1);setOptions(data.options??{brands:[],classifications:[]});setIndicatorCounts(data.indicators??{baseline:0,launch:0,phaseout:0,unclassified:0,imagesUnavailable:0,divergent:0});setLoading(false)},[query]);
  useEffect(()=>{const timer=setTimeout(()=>{void load()},search?300:0);return()=>clearTimeout(timer)},[load,search]);
  const visible=items;
  function chooseIndicator(value:Indicator){setIndicator((current)=>current===value?"":value);setSearch("");setBrand("");setClassification("");setStock("");setReview("");setSelected([]);setPage(1)}
  async function selectFiltered(){const params=query(false);params.set("keys","1");const response=await fetch(`/api/products?${params}`,{cache:"no-store"});const data=await response.json();setSelected(data.skuKeys??[]);setToast(`${(data.skuKeys??[]).length.toLocaleString("pt-BR")} produtos filtrados selecionados.`)}
  async function inactivate(){if(!selected.length)return;const response=await fetch("/api/inactive-products",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({skuKeys:selected})});const data=await response.json();if(response.ok){setSelected([]);setToast(`${data.updated} produtos movidos para Itens inativos.`);void load()}else setToast(data.error)}
  async function exportSelected(){const response=await fetch("/api/exports",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({skuKeys:selected})});const data=await response.json();if(!response.ok)return setToast(data.error);location.href=data.downloadUrl}
  return <>{run&&<p className="mb-3 text-xs font-semibold text-gray-500">Dados da atualização concluída em {run.finishedAt?new Date(run.finishedAt).toLocaleString("pt-BR"):"processamento"}.</p>}{editing&&<ProductEditor product={editing} onClose={()=>setEditing(null)} onSaved={(message)=>{setToast(message);void load()}}/>}{toast&&<div className="mb-4 flex items-center justify-between rounded-xl bg-[#e7f8f8] p-3 text-sm font-semibold text-[#147f81]"><span>{toast}</span><button onClick={()=>setToast("")}><X size={16}/></button></div>}
    {mode==="pending"&&<div className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{([{key:"baseline",label:"Baseline não cadastrado",count:indicatorCounts.baseline},{key:"launch",label:"Lançamentos (New + Launch)",count:indicatorCounts.launch},{key:"phaseout-stock",label:"Fora de linha com estoque",count:indicatorCounts.phaseout},{key:"unclassified-stock",label:"Sem classificação com estoque",count:indicatorCounts.unclassified},{key:"images-unavailable",label:"Todas as fotos indisponíveis",count:indicatorCounts.imagesUnavailable}] as {key:Indicator;label:string;count:number}[]).map((card)=><button type="button" key={card.key} onClick={()=>chooseIndicator(card.key)} className={`card text-left transition ${indicator===card.key?"border-[#1fadad] ring-2 ring-[#1fadad]/20":"hover:border-[#1fadad]"}`}><span className="text-3xl font-black text-[#1fadad]">{card.count.toLocaleString("pt-BR")}</span><span className="mt-1 block text-sm font-bold text-gray-700">{card.label}</span><span className="mt-2 block text-xs text-gray-500">Clique para {indicator===card.key?"remover o filtro":"ver somente estes itens"}</span></button>)}</div>}
    {mode==="validation"&&<button type="button" onClick={()=>chooseIndicator("id-divergent")} className={`card mb-4 w-full text-left transition sm:max-w-sm ${indicator==="id-divergent"?"border-[#1fadad] ring-2 ring-[#1fadad]/20":"hover:border-[#1fadad]"}`}><span className="text-3xl font-black text-[#1fadad]">{indicatorCounts.divergent.toLocaleString("pt-BR")}</span><span className="mt-1 block text-sm font-bold text-gray-700">SKUs com ID diferente entre os sistemas</span><span className="mt-2 block text-xs text-gray-500">Clique para {indicator==="id-divergent"?"remover o filtro":"ver somente os incorretos"}</span></button>}
    <div className="card mb-4 grid gap-3 md:grid-cols-2 xl:grid-cols-5"><input className="input" value={search} onChange={(event)=>{setSearch(event.target.value);setPage(1)}} placeholder="Buscar SKU, EAN ou produto"/><select className="input" value={brand} onChange={(event)=>{setBrand(event.target.value);setPage(1)}}><option value="">Todas as marcas</option>{options.brands.map((value)=><option key={value}>{value}</option>)}</select><select className="input" value={classification} onChange={(event)=>{setClassification(event.target.value);setPage(1)}}><option value="">Todas as classificações</option>{options.classifications.map((value)=><option key={value}>{value}</option>)}</select><select className="input" value={stock} onChange={(event)=>{setStock(event.target.value);setPage(1)}}><option value="">Todo estoque</option><option value="positive">Com estoque</option><option value="zero">Sem estoque</option></select><select className="input" value={review} onChange={(event)=>{setReview(event.target.value);setPage(1)}}><option value="">Todos os produtos</option><option value="yes">Com informações a revisar</option><option value="no">Sem revisão necessária</option></select></div>
    {mode==="pending"&&<div className="mb-4 flex flex-wrap gap-2"><button className="btn btn-secondary" onClick={selectFiltered}>Selecionar filtrados ({total.toLocaleString("pt-BR")})</button><button className="btn btn-secondary" disabled={!selected.length} onClick={inactivate}><Ban size={16}/>Não cadastrar ({selected.length})</button><button className="btn btn-primary" disabled={!selected.length} onClick={exportSelected}>Exportar ({selected.length})</button></div>}
    <div className="table-wrap">{loading?<p className="p-8 text-center text-gray-500">Carregando…</p>:<table><thead><tr>{mode==="pending"&&<th></th>}<th>SKU</th>{mode==="validation"&&<><th>ID Senior</th><th>ID Tiny</th></>}<th>Produto</th>{mode==="pending"&&<th>Fotos</th>}<th>Marca</th><th>Classificação</th><th>Estoque</th><th>Status</th><th></th></tr></thead><tbody>{visible.length?visible.map((item)=><tr key={item.id}>{mode==="pending"&&<td><input type="checkbox" checked={selected.includes(item.skuKey)} onChange={(event)=>setSelected((current)=>event.target.checked?[...current,item.skuKey]:current.filter((key)=>key!==item.skuKey))}/></td>}<td className="font-bold">{item.sku}</td>{mode==="validation"&&<><td>{item.seniorTinyId||"—"}</td><td>{item.tinyId||"—"}</td></>}<td><div className="font-semibold">{item.name}</div>{item.needsReview&&<span className="badge badge-red mt-1">Informações a revisar</span>}</td>{mode==="pending"&&<td>{item.availableImageUrl?<a href={item.availableImageUrl} target="_blank" rel="noreferrer" title="Abrir imagem em nova aba"><img src={item.availableImageUrl} alt={item.name} loading="lazy" className="h-12 w-12 rounded-lg border bg-white object-contain transition hover:scale-105"/></a>:item.allImagesUnavailable?<span className="badge badge-red">Indisponíveis</span>:<span className="text-xs text-gray-400">Verificando…</span>}</td>}<td>{item.brand||"—"}</td><td>{item.classification||"—"}</td><td className="font-bold">{item.stock??"—"}</td><td><span className={item.validationStatus==="CORRECT"?"badge badge-green":"badge badge-orange"}>{mode==="validation"?item.validationStatus:item.comparisonStatus}</span></td><td>{item.needsReview&&<button className="font-bold text-[#1fadad]" onClick={()=>setEditing(item)}>Revisar</button>}</td></tr>):<tr><td colSpan={mode==="validation"?9:9} className="py-12 text-center text-gray-500">Nenhum registro encontrado com estes filtros.</td></tr>}</tbody></table>}</div>
    <div className="mt-4 flex flex-wrap items-center justify-between gap-3"><span className="text-sm text-gray-500">{total.toLocaleString("pt-BR")} produtos • página {page} de {totalPages}</span><div className="flex gap-2"><button className="btn btn-secondary" disabled={page<=1||loading} onClick={()=>setPage((value)=>Math.max(1,value-1))}>Anterior</button><button className="btn btn-secondary" disabled={page>=totalPages||loading} onClick={()=>setPage((value)=>Math.min(totalPages,value+1))}>Próxima</button></div></div>
  </>;
}
