"use client";
import { useState } from "react";

const sourceTypes = [
  ["SENIOR","Base de produtos Senior"],["TINY","Base de produtos Tiny"],["STOCK","Base de estoque"],["CLASSIFICATION","Classificação"],["PRICE_COST","Preços e custos"],
] as const;
type Source = {id:string;type:string;name:string;spreadsheetUrl:string;sheetName:string;columnMapping:Record<string,string>;active:boolean};

export function SourcesManager({initial}:{initial:Source[]}){
  const [sources,setSources]=useState(initial); const [message,setMessage]=useState("");
  async function save(type:string, form:HTMLFormElement){const data=Object.fromEntries(new FormData(form));const mapping={sku:data.sku,ean:data.ean,name:data.name,brand:data.brand,category:data.category,weight:data.weight,length:data.length,width:data.width,height:data.height,tinyId:data.tinyId,stock:data.stock,classification:data.classification,price:data.price,cost:data.cost};const response=await fetch("/api/data-sources",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type,name:data.name,spreadsheetUrl:data.spreadsheetUrl,sheetName:data.sheetName,columnMapping:mapping,active:true})});const result=await response.json();setMessage(response.ok?"Fonte salva.":result.error);if(response.ok)setSources((current)=>[...current.filter((item)=>item.type!==type),result]);}
  async function test(form:HTMLFormElement){const data=Object.fromEntries(new FormData(form));setMessage("Testando conexão…");const response=await fetch("/api/data-sources/test",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({spreadsheetUrl:data.spreadsheetUrl,sheetName:data.sheetName})});const result=await response.json();setMessage(response.ok?`Conexão OK: ${result.count} linhas. Colunas: ${result.columns.join(", ")}`:result.error);}
  return <div className="space-y-4">{message&&<div className="rounded-xl border border-orange-200 bg-orange-50 p-3 text-sm text-orange-800">{message}</div>}{sourceTypes.map(([type,label])=>{const source=sources.find((item)=>item.type===type);const mapping=source?.columnMapping??{};return <details className="card" key={type} open={!source}><summary className="flex cursor-pointer list-none items-center justify-between font-bold"><span>{label}</span><span className={source?"badge badge-green":"badge"}>{source?"Configurada":"Pendente"}</span></summary><form className="mt-5 space-y-4" onSubmit={(e)=>{e.preventDefault();save(type,e.currentTarget)}}><input type="hidden" name="name" value={label}/><div className="grid gap-4 lg:grid-cols-[2fr_1fr]"><div><label className="label">Link público do Google Sheets</label><input className="input" name="spreadsheetUrl" defaultValue={source?.spreadsheetUrl} placeholder="https://docs.google.com/spreadsheets/d/..." required/></div><div><label className="label">Nome exato da aba</label><input className="input" name="sheetName" defaultValue={source?.sheetName} required/></div></div><p className="text-xs font-bold uppercase tracking-wider text-gray-500">Mapeamento de colunas</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{["sku","ean","name","brand","category","weight","length","width","height","tinyId","stock","classification","price","cost"].map((field)=><div key={field}><label className="label">{field}</label><input className="input" name={field} defaultValue={mapping[field]??""} placeholder="Título na planilha"/></div>)}</div><div className="flex flex-wrap gap-2"><button className="btn btn-primary" type="submit">Salvar fonte</button><button className="btn btn-secondary" type="button" onClick={(e)=>test(e.currentTarget.form!)}>Testar e visualizar</button></div></form></details>})}</div>
}
